name: generic-report-generator

services:
  # --- Infrastructure ---
  postgres:
    image: postgres:18.1-alpine
    container_name: report-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: reportdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d reportdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.4.0-alpine
    container_name: report-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    container_name: report-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # --- Application ---
  api:
    image: report-api:dev
    container_name: report-api
    build:
      context: ../
      dockerfile: src/GenericReportGenerator.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=postgres;Database=reportdb;Username=admin;Password=admin
      - RabbitMq__Host=rabbitmq
      - RabbitMq__VirtualHost=/
      - RabbitMq__Username=admin
      - RabbitMq__Password=admin
      - ReportFiles__BasePath=/app/generated_reports
      - Serilog__WriteTo__0__Args__formatter=Serilog.Formatting.Compact.RenderedCompactJsonFormatter,Serilog.Formatting.Compact
    volumes:
      - ../assets/generated_reports:/app/generated_reports
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  worker:
    image: report-worker:dev
    container_name: report-worker
    build:
      context: ../
      dockerfile: src/GenericReportGenerator.Worker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=postgres;Database=reportdb;Username=admin;Password=admin
      - ConnectionStrings__Redis=redis:6379
      - RabbitMq__Host=rabbitmq
      - RabbitMq__VirtualHost=/
      - RabbitMq__Username=admin
      - RabbitMq__Password=admin
      - ReportFiles__BasePath=/app/generated_reports
    volumes:
      - ../assets/generated_reports:/app/generated_reports
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    image: report-migrations:dev
    container_name: report-migrations
    build:
      context: ../
      dockerfile: src/GenericReportGenerator.Migrations/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=postgres;Database=reportdb;Username=admin;Password=admin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  rabbitmq_data: